### ISSUE TITLE
Checkout if cloud manager is feasible to help us out with backups

### ISSUE THREAD

**Issue by ghost** [NSLS-II-LIX/mongobak#4]
https://www.mongodb.com/cloud/?_ga=1.108357954.1722052486.1461867664

**Comment by hhslepicka** [comment]
@arkilic news? I'm thinking about closing this issue.

**Comment by ghost** [comment]
No $$

**Comment by hhslepicka** [comment]
![image](https://cloud.githubusercontent.com/assets/8185425/18358535/8244f7de-75c3-11e6-93f9-b9920fc55fed.png)
